import { useRef, useState, useCallback, useEffect } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { useNavigate } from 'react-router-dom'
import { yupResolver } from '@hookform/resolvers/yup'
import * as yup from 'yup'
import Alert from '@mui/material/Alert'
import Avatar from '@mui/material/Avatar'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import Paper from '@mui/material/Paper'
import TextField from '@mui/material/TextField'
import Typography from '@mui/material/Typography'
import { useAuth } from '@/context/AuthContext'
import { APP_NAME, ONBOARDING_LABELS } from '@/constants/const'
import { useGetProfile } from '@/hooks/useGetProfile'
import { useUpdateProfile } from '@/hooks/useUpdateProfile'
import { useUploadAvatar } from '@/hooks/useUploadAvatar'

interface OnboardingValues {
  username: string
}

const onboardingSchema = yup.object({
  username: yup
    .string()
    .min(3, ONBOARDING_LABELS.usernameMin)
    .max(30, ONBOARDING_LABELS.usernameMax)
    .matches(/^[a-zA-Z0-9_]+$/, ONBOARDING_LABELS.usernameFormat)
    .required(ONBOARDING_LABELS.usernameRequired),
})

function isAutoGeneratedUsername(username: string): boolean {
  return /_[0-9a-f]{4}$/.test(username)
}

export function OnboardingPage() {
  const fileInputRef = useRef<HTMLInputElement>(null)

  const [avatarFile, setAvatarFile] = useState<File | null>(null)
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null)

  const { user } = useAuth()
  const navigate = useNavigate()
  const { data: profile, isPending: profileLoading } = useGetProfile(user?.id)
  const updateProfile = useUpdateProfile()
  const uploadAvatar = useUploadAvatar()

  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<OnboardingValues>({
    defaultValues: { username: '' },
    resolver: yupResolver(onboardingSchema),
  })

  useEffect(() => {
    if (!profileLoading && profile && !isAutoGeneratedUsername(profile.username)) {
      navigate('/map', { replace: true })
    }
  }, [profile, profileLoading, navigate])

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0]
      if (!file) return
      setAvatarFile(file)
      setAvatarPreview(URL.createObjectURL(file))
    },
    []
  )

  const onSubmit = handleSubmit(async ({ username }) => {
    if (!user) return

    let avatarUrl: string | undefined
    if (avatarFile) {
      try {
        avatarUrl = await uploadAvatar.mutateAsync({ userId: user.id, file: avatarFile })
      } catch {
        return
      }
    }

    updateProfile.mutate(
      {
        userId: user.id,
        updates: { username, ...(avatarUrl !== undefined && { avatar_url: avatarUrl }) },
      },
      { onSuccess: () => void navigate('/map', { replace: true }) }
    )
  })

  if (!user || profileLoading) return null

  const isPending = updateProfile.isPending || uploadAvatar.isPending
  const error = updateProfile.error ?? uploadAvatar.error

  return (
    <Box
      sx={{
        minHeight: '100dvh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        p: 2,
      }}
    >
      <Paper sx={{ p: { xs: 3, sm: 4 }, maxWidth: 440, width: '100%' }}>
        <Typography variant="h4" gutterBottom>
          {APP_NAME}
        </Typography>
        <Typography variant="h6" gutterBottom>
          {ONBOARDING_LABELS.title}
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
          {ONBOARDING_LABELS.subtitle}
        </Typography>

        {error && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {error.message}
          </Alert>
        )}

        <Box
          component="form"
          onSubmit={onSubmit}
          noValidate
          sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}
        >
          <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1 }}>
            <Avatar
              src={avatarPreview ?? undefined}
              sx={{ width: 80, height: 80, cursor: 'pointer' }}
              onClick={() => fileInputRef.current?.click()}
            />
            <Button
              type="button"
              variant="text"
              size="small"
              onClick={() => fileInputRef.current?.click()}
            >
              {ONBOARDING_LABELS.choosePhoto}
            </Button>
            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp"
              style={{ display: 'none' }}
              onChange={handleFileChange}
            />
          </Box>

          <Controller
            name="username"
            control={control}
            render={({ field }) => (
              <TextField
                {...field}
                label={ONBOARDING_LABELS.usernameLabel}
                autoComplete="username"
                error={!!errors.username}
                helperText={errors.username?.message ?? ONBOARDING_LABELS.usernameHelp}
                fullWidth
              />
            )}
          />

          <Button
            type="submit"
            variant="contained"
            size="large"
            disabled={isPending}
            fullWidth
          >
            {ONBOARDING_LABELS.completeButton}
          </Button>
        </Box>
      </Paper>
    </Box>
  )
}
